// mockData.ts
import { Store } from "./types";

export const MOCK_STORES: Store[] = [
  {
    id: "s1",
    name: "Nomad Tech",
    logo: "🖥️",
    category: "Электроник",
    rating: 4.8,
    productCount: 24,
    isVerified: true,
    products: [
      {
        id: "p1",
        name: "Wireless Earbuds Pro",
        price: 89000,
        image: "🎧",
        category: "Аудио",
        inStock: true,
      },
      {
        id: "p2",
        name: "USB-C Hub 7-in-1",
        price: 45000,
        image: "🔌",
        category: "Аксессуар",
        inStock: true,
      },
      {
        id: "p3",
        name: "Mechanical Keyboard",
        price: 129000,
        image: "⌨️",
        category: "Компьютер",
        inStock: false,
      },
      {
        id: "p4",
        name: "4K Webcam",
        price: 75000,
        image: "📷",
        category: "Компьютер",
        inStock: true,
      },
    ],
  },
  {
    id: "s2",
    name: "Steppe Wear",
    logo: "👗",
    category: "Хувцас",
    rating: 4.6,
    productCount: 58,
    isVerified: true,
    products: [
      {
        id: "p5",
        name: "Cashmere Hoodie",
        price: 156000,
        image: "🧥",
        category: "Дээд хувцас",
        inStock: true,
      },
      {
        id: "p6",
        name: "Wool Cargo Pants",
        price: 98000,
        image: "👖",
        category: "Доод хувцас",
        inStock: true,
      },
      {
        id: "p7",
        name: "Felt Cap",
        price: 34000,
        image: "🧢",
        category: "Малгай",
        inStock: true,
      },
      {
        id: "p8",
        name: "Leather Belt",
        price: 28000,
        image: "👜",
        category: "Аксессуар",
        inStock: false,
      },
    ],
  },
  {
    id: "s3",
    name: "Ulaan Kitchen",
    logo: "🍳",
    category: "Гэр ахуй",
    rating: 4.5,
    productCount: 31,
    isVerified: false,
    products: [
      {
        id: "p9",
        name: "Cast Iron Pot Set",
        price: 210000,
        image: "🫕",
        category: "Тогоо",
        inStock: true,
      },
      {
        id: "p10",
        name: "Bamboo Cutting Board",
        price: 22000,
        image: "🪵",
        category: "Хэрэгсэл",
        inStock: true,
      },
      {
        id: "p11",
        name: "Spice Rack",
        price: 44000,
        image: "🌿",
        category: "Хэрэгсэл",
        inStock: true,
      },
      {
        id: "p12",
        name: "Electric Kettle",
        price: 67000,
        image: "☕",
        category: "Цахилгаан",
        inStock: false,
      },
    ],
  },
];
